### ISSUE TITLE
Demo Script

### ISSUE THREAD

**Issue by gauenk** [hjnnjh/Particle-Filter-for-IBHP#1]
This is such a nice repo! Way to go. Do you have a demo script or a readme for this?

**Comment by hjnnjh** [comment]
> This is such a nice repo! Way to go. Do you have a demo script or a readme for this?

Still have some problems that need to be solved, I'll push a demo script and a readme later.

**Comment by hjnnjh** [comment]
> This is such a nice repo! Way to go. Do you have a demo script or a readme for this?

I improved the structure of this repo and wrote an explainable README. Now you can take a look at it.

**Comment by gauenk** [comment]
The demo script runs on my laptop! It is very cool. I was just checking the code and had two questions. First: is [this line of code the Poisson Process](https://github.com/hjnnjh/Particle-Filter-for-IBHP/blob/4043c4802c81a490eb28c70201cd0ec2ec692b4f/code/IBHP_simulation_torch.py#L86)? 

Second, will you also be adding test scripts? How do I know your simulator is sampling from the IBHP? Are there statistics of the process you can compute against groundtruth? I didn't see these tests in there, but maybe I just haven't found them.

**Comment by hjnnjh** [comment]
> The demo script runs on my laptop! It is very cool. I was just checking the code and had two questions. First: is [this line of code the Poisson Process](https://github.com/hjnnjh/Particle-Filter-for-IBHP/blob/4043c4802c81a490eb28c70201cd0ec2ec692b4f/code/IBHP_simulation_torch.py#L86)?

Yes. Hawkes Process is a special case of the nonhomogeneous Poisson process, and the thinning process is an intensity-based algorithm to simulate Hawkes Process. But for IBHP, the form of conditional intensity function is changeable, so I'm not sure this algorithm is proper for IBHP simulation.

> Second, will you also be adding test scripts? How do I know your simulator is sampling from the IBHP? Are there statistics of the process you can compute against groundtruth? I didn't see these tests in there, but maybe I just haven't found them.

The simulator strictly follows the generation process mentioned in the IBHP paper where the author set the model parameters and uses the generation process to generate simulated observations. The main purpose of the simulating experiment is to verify that SMC can effectively make the model parameters converge to the hypothetical values used to generate the simulated data. The simulated intensity, factor occurrence, and other IBHP states are all included in the class `IBHPTorch`. I only provided two functions to plot simulated statistics. If you want to check more details, you need to extract the attributes you want and use them to compute statistics results. 

Hope the above can help you!

**Comment by gauenk** [comment]
That is such a detailed comment -- thank you. 

My question is about code testing, rather than the purpose of your code.

I recognize your goal is to sample from the IBHP but how would I check you have properly achieved this goal?

**Comment by hjnnjh** [comment]
> That is such a detailed comment -- thank you.
> 
> My question is about code testing, rather than the purpose of your code.
> 
> I recognize your goal is to sample from the IBHP but how would I check you have properly achieved this goal?

The author doesn't mention how he checks the correctness of the generation process. So I think the most appropriate approach to achieve it is using SMC to estimate the model parameters, and check whether the result is close to the hypothetical values.

**Comment by gauenk** [comment]
It seems risky to test complicated code (the IBHP) with complicated code (the SMC sampler) but I appreciate this is difficult to check in general
